org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1

minecraft_version_range=[26.1,26.1.2]
neo_version=26.1.0.19-beta
loader_version_range=[1,)
neo_version_range=[21,)

mod_id=noblind
mod_name=NoBlind
mod_license=MIT
mod_version=1.0.0

mod_group_id=cardejibka.noblind
mod_authors=CardeJIbka
mod_description=Removes blindness and darkness status effects visuals completely.
